![Itq](img/LogoITQ.jpg)

**Programa 2 - Estandarización**

![Python](img/python_logo.png)

* *Nombre:* Judith Piedra
* *Fecha :* **23-09-2026**
* *Repositorio:* <a href= "https://github.com/MerakiDevJP/machine2_23092026nocturno.git"> Link del repositorio Github</a>
* https://github.com/MerakiDevJP/machine2_23092026nocturno.git

## APLICACIÓN DE LA ESTANDARIZACIÓN

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
# Carga de datos.
X_train = np.array([[ 1., -1., 2.],
                    [ 2., 0., 0.],
                    [ 0., 1., -1.]])
print("Datos de entrenamiento")
print(X_train)

Datos de entrenamiento
[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


In [3]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()
print(standardizer)

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print("Media de cada característica: ", standardizer.mean_)
print("Desviación estándar de cada característica: ", standardizer.scale_)
print("Datos estandarizados")
print(X_train_std)


StandardScaler()
Media de cada característica:  [1.         0.         0.33333333]
Desviación estándar de cada característica:  [0.81649658 0.81649658 1.24721913]
Datos estandarizados
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [4]:
X_train_2 = np.array([[ 1., -1., 2.],
                      [ 2., 0., 0.],
                      [ 0., 1., -1.]])

In [5]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train_2)

X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)


[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [6]:
# Comprobar si las matrices estandarizadas son iguales
print(np.array_equiv(X_train_std, X_train_2_std))

True
