![Itq](img/LogoITQ.jpg)

**Programa 1 - Normalización**

![Python](img/python_logo.png)

* *Nombre:* Judith Piedra
* *Fecha :* **23-09-2026**
* *Repositorio:* <a href= "https://github.com/MerakiDevJP/machine2_23092026nocturno.git"> Link del repositorio Github</a>
* https://github.com/MerakiDevJP/machine2_23092026nocturno.git

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
 # Carga de datos.
X_train = np.array([[ 1.,-4., 5.],
[ 5., 0., 2.],
[ 0., 6.,-3.]])
print("Datos de entrenamiento")
print(X_train)

Datos de entrenamiento
[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [3]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
print(normalizer)

X_train_norm = normalizer.fit_transform(X_train)
# Atributos 
print("Atributos")
print("Mínimos:", normalizer.data_min_)
print("Máximos:", normalizer.data_max_)
print("Rango (feature_range):", normalizer.feature_range)

MinMaxScaler()
Atributos
Mínimos: [ 0. -4. -3.]
Máximos: [5. 6. 5.]
Rango (feature_range): (0, 1)


In [4]:
 # Salida de resultados.
print("Datos normalizados")
print(X_train_norm)

Datos normalizados
[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [5]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos"fit" y "transform" por separado
X_train_2 = np.copy(X_train)
print("Datos de entrenamiento")
print(X_train_2)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(X_train_2)
print(f)

X_train_norm_2 = f.transform(X_train_2)
print("Atributos")
print("Mínimos:", normalizer.data_min_)
print("Máximos:", normalizer.data_max_)
print("Rango (feature_range):", normalizer.feature_range)
print(X_train_norm_2)

# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

Datos de entrenamiento
[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]
MinMaxScaler()
Atributos
Mínimos: [ 0. -4. -3.]
Máximos: [5. 6. 5.]
Rango (feature_range): (0, 1)
[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]
True


In [6]:
 # Normalizar un nuevo conjunto de datos de test (SOLO HAY QUE APLICAR EL MÉTODO"transform", NO EL "fit")
X_test = np.array([[ 1.,-3., 2.],
[ 3., 0., 0.],
[ 0., 4.,-1.]])
print("Datos de prueba")
print(X_test)

# Normalizar los datos de "X_test"
X_test_norm = normalizer.transform(X_test)

# Mostrar los resultados normalizados
print("")
print("Datos normalizados")
print(X_test_norm)

Datos de prueba
[[ 1. -3.  2.]
 [ 3.  0.  0.]
 [ 0.  4. -1.]]

Datos normalizados
[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]
